#input and output file names
input file location: histos_new_process_v3
input file label: new_process_v3
output file location: pdf_new_process_v3

#drawing options
skip systematics: false
draw ratio plot: true
draw legend: true
log scale: false
save png: true
save pdf: true
blinded: false
KS test: false
selection info : false
SF info: false

#luminosity and era
luminosity: 19.5
luminosity error: 0.044
trigger SF error: 0.02
lumi era string: "                #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}"

#Lepton categories: "draw name"
lepton categories:
    mu_mu: " #mu #mu "
    mu_ele: " #mu e "
    ele_ele: " e e "

#Jet-tag categories: "draw name"
jet tag categories:
    ge4j: " + #geq4 jets"
    eq3j: " + 3 jets"
    #eq2jeq2t : " + 2 jets + 2 b-tags"
    #eq3jeq2t : " + 3 jets + 2 b-tags"
    #ge4jeq2t : " + #geq4 jets + 2 b-tags"
    #ge3t : " + #geq3 jets + #geq3 b-tags"

#Systematics used in error bars
systematics:
    - weight_PUup
    - weight_PUdown
    - topPtWgtDown
    - topPtWgtUp

# Samples drawn on top, scaling (1.0, 2.0, "norm" for area-normalized) 
signal samples:
    ttH125:
        draw name: "t#bar{t}H125"
        color: kRed
        stack or line: stack
        line width: 2 # must be integer
        scale: 1.0

#Samples in each group will be added together and appear as a single entry in the stack plot
background sample groups:
    Others:
        draw name: Others
        color: kSpring+8
        systematics: all
        samples:
            - tbZ_ll
            #- WpWpqq
            #- WmWmqq
            #- WWDPI

    triboson:
        draw name: triboson
        color: kViolet
        systematics: all
        samples:
            - www
            - wwz

    #ttbarGStar:
        #draw name: "t#bar{t}G*"
        #color: kCyan-3
        #systematics: all
        #samples:
            #- ttbarGStar_ee
            #- ttbarGStar_mm
            #- ttbarGStar_tt

#Samples, ordered bottom-to-top
background samples:
    MuEG_QF_sideband:
        draw name: "Q flip"
        color: kGray+1
        systematics: 40PercentRateUp+40PercentRateDown

    DoubleElectron_QF_sideband:
        draw name: "Q flip"
        color: kGray+1
        systematics: 40PercentRateUp+40PercentRateDown

    DoubleMu_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: 40PercentRateUp+40PercentRateDown

    MuEG_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: 40PercentRateUp+40PercentRateDown

    DoubleElectron_NP_sideband:
        draw name: "Fakes"
        color: kGray
        systematics: 40PercentRateUp+40PercentRateDown

    wz:
        draw name: "WZ"
        color: kViolet-4
        systematics: all

    #zz_llll:
        #draw name: "ZZ"
        #color: kAzure-9
        #systematics: all

    ttbarG:
        draw name: "t#bar{t}G"
        color: kGray+3
        systematics: all

    ttbarZ:
        draw name: "t#bar{t}Z"
        color: kSpring+2
        systematics: all

    ttbarW:
        draw name: "t#bar{t}W"
        color: kGreen-5
        systematics: all

    ttbarWW:
        draw name: "t#bar{t}WW"
        color: kBlue-9
        systematics: all


#distribution: [title, underflow, overflow]
distributions:
    numJets: [number of jets, false, false]
    numLooseBJets: [number of loose b-tagged jets, false, false]
    numMediumBJets: [number of medium b-tagged jets, false, false]
    sum_lep1pt_lep2pt_met: ['Sum pT (lepton 1, lepton 2, MET)', false, false]
    all_leptons_by_pt_1_SIP: ['First lepton SIP', false, false]
    all_leptons_by_pt_1_lepMVA: [First lepton MVA, false, false]
    all_leptons_by_pt_2_lepMVA: [Second lepton MVA, false, false]
    all_leptons_by_pt_1_pt: [First lepton pT, 20, false, false]
    all_leptons_by_pt_2_pt: [Second lepton pT, 20, false, false]
    all_leptons_by_pt_1_eta: [First lepton pseudorapidity, false, false]
    jets_by_pt_1_btagCombinedSecVertex: [First jet b-tag discriminant, false, false]
    jets_by_pt_2_btagCombinedSecVertex: [Second jet b-tag discriminant, false, false]
    jets_by_pt_3_btagCombinedSecVertex: [Third jet b-tag discriminant, false, false]
    jets_by_pt_1_pt: [First jet pT, false, false]
    jets_by_pt_2_pt: [Second jet pT, false, false]
    jets_by_pt_3_pt: [Third jet pT, false, false]

