#input and output file names
input file location: histos_OS_studies
input file label: OS_v0
output file location: pdf_OS_studies

#drawing options
skip systematics: true
draw ratio plot: true
draw legend: true
log scale: false
save png: true
save pdf: true
blinded: false
KS test: false
selection info : false
SF info: false

#luminosity and era
luminosity: 19.5
luminosity error: 0.044
trigger SF error: 0.02
lumi era string: "                #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}"

#Lepton categories: "draw name"
lepton categories:
    mu_mu: " #mu #mu "
    mu_ele: " #mu #ele "
    ele_ele: " e e "

#Jet-tag categories: "draw name"
jet tag categories:
    eq3jeq2t: " + #eq3 jets + #eq2 tags"
    ge4jeq2t: " + #geq4 jets + #eq2 tags"
    ge3t: " + #geq3 tags"

#Systematics used in error bars
systematics:
    - nominal
    #- weight_PUup
    #- weight_PUdown
    #- topPtWgtDown
    #- topPtWgtUp

# Samples drawn on top, scaling (1.0, 2.0, "norm" for area-normalized) 

signal samples:
    ttH125:
        draw name: "t#bar{t}H125"
        color: kBlue
        stack or line: line
        line width: 2 # must be integer
        scale: norm

#Samples in each group will be added together and appear as a single entry in the stack plot
background sample groups:
    Wjets:
        draw name: Wjets
        color: kGreen
        systematics: all
        samples:
            - wjets_0p
            - wjets_1p
            - wjets_2p
            - wjets_3p
            - wjets_4p
    diboson:
        draw name: diboson
        color: kAzure+2
        systematics: all
        samples:
            - ww
            - wz
            - zz

    Zjets:
        draw name: Zjets
        color: kBlue
        systematics: all
        samples:
            - zjets_0p
            - zjets_1p
            - zjets_2p
            - zjets_3p
            - zjets_4p
            - zjets_lowmass

    single_top:
        draw name: single_top
        color: kMagenta
        systematics: all
        samples:
            - singlet_s
            - singlet_t
            - singlet_tW
            - singletbar_s
            - singletbar_t
            - singletbar_tW

    ttbar:
        draw name: ttbar
        color: kRed-7
        systematics: all
        samples:
            - ttbar_jj
            - ttbar_lj
            - ttbar_ll

    ttbar_cc:
        draw name: ttbar_cc
        color: kRed+1
        systematics: all
        samples:
            - ttbar_cc_jj
            - ttbar_cc_lj
            - ttbar_cc_ll

    ttbar_b:
        draw name: ttbar_b
        color: kRed-2
        systematics: all
        samples:
            - ttbar_b_jj
            - ttbar_b_lj
            - ttbar_b_ll

    ttbar_bb:
        draw name: ttbar_bb
        color: kRed+3
        systematics: all
        samples:
            - ttbar_bb_jj
            - ttbar_bb_lj
            - ttbar_bb_ll

#Samples, ordered bottom-to-top
background samples:
    ttbarZ:
        draw name: "t#bar{t}Z"
        color: kBlue-10
        systematics: all

    ttbarW:
        draw name: "t#bar{t}W"
        color: kBlue-10
        systematics: all

#distribution: [title, underflow, overflow]
distributions:
    numJets: [number of jets, false, false]
    numMediumBJets: [number of medium b-tagged jets, false, false]
    numAllLeptons: [number of leptons, false, false]
    leptons_by_pt_1_pt: [First lepton pT, false, false]
    leptons_by_pt_2_pt: [Second lepton pT, false, false]
    leptons_by_pt_1_eta: [First lepton eta, false, false]
    leptons_by_pt_2_eta: [Second lepton eta, false, false]
    jets_by_pt_1_pt: [First jet pT, false, false]
    jets_by_pt_2_pt: [Second jet pT, false, false]
    jets_by_pt_3_pt: [Third jet pT, false, false]
    mass_leplep: [dilepton mass, false, false]
    dR_leplep: [dR between leptons, false, false]
    met_pt: [MET, false, false]
    mht: [MHT, false, false]
    sum_pt: [Sum pT (tight), false, false]


