#input and output file names
input file location: ../histos_3l_ttZ_studies_3t_lepCut_forLimits
input file label: ttV_lepCuts_v1

lepton categories:
    3l:
        data sample: inclusive_data
        excluded samples: [3rd_spot] #[ttbarG, 3rd_spot]
        category name: 'ttZ_3l'
        
#Jet-tag categories: "draw name"
jet tag categories:
    #eq3j_metLD_bloose: " + #eq3 jets"
    #ge4j_metLD_bloose: " + #geq4 jets"
    eq3j_bloose: " + #eq3 jets"
    ge4j_bloose: " + #geq4 jets"

#Systematics used in error bars
systematics:
    - nominal
    - weight_PU
    - topPtWgt
    - csvWeightHF
    - csvWeightLF

ttH mass points: ##New code to automate masses
    - '125'
    
data samples:
    inclusive_data:
        datacard name: "data_obs"
        systematics: common
        samples: [inclusive_data]

signal samples:
    ttbarZ:
        datacard name: "TTZ"
        systematics: common
        samples: [ttbarZ]
        scale: 1.0

#Samples, ordered bottom-to-top
background samples:
    inclusive_data_NP_sideband:
        datacard name: "FR_data"
        systematics: 40PercentRate
        samples: [inclusive_data_NP_sideband]
        scale: 1.0

#     Others:
#         datacard name: "Rare SM"
#         systematics: common
#         samples: [www, wwz, tbZ_ll, WpWpqq, WWDPI] #WmWmqq

    3rd_spot:
        datacard name: "3rd_spot"
        systematics: common
        samples: [3rd_spot] #WmWmqq
        scale: 1.0

#     ## Not enough MC events; makes combine tool seg fault
#     WWqq:
#         datacard name: "WWqq"
#         systematics: common
#         samples: [WpWpqq] #WmWmqq

    tbZ_ll:
        datacard name: "TBZ"
        systematics: common
        samples: [tbZ_ll]
        scale: 1.0

    zz_llll:
        datacard name: "ZZ"
        systematics: common
        samples: [zz_llll]
        scale: 1.0

#     zz_lf_llll:
#         datacard name: "ZZ_LF"
#         systematics: common
#         samples: [zz_lf_llll]

#     zz_cc_llll:
#         datacard name: "ZZ_CC"
#         systematics: common
#         samples: [zz_cc_llll]

#     zz_b_llll:
#         datacard name: "ZZ_B"
#         systematics: common
#         samples: [zz_b_llll]

#     zz_bb_llll:
#         datacard name: "ZZ_BB"
#         systematics: common
#         samples: [zz_bb_llll]

#     wz_lll:
#         datacard name: "WZ"
#         systematics: common
#         samples: [wz_lll]

    wz_lf_lll:
        datacard name: "WZ_LF"
        systematics: common
        samples: [wz_lf_lll]
        scale: 1.0

    wz_cc_lll:
        datacard name: "WZ_CC"
        systematics: common
        samples: [wz_cc_lll]
        scale: 1.0

    wz_b_lll:
        datacard name: "WZ_B"
        systematics: common
        samples: [wz_b_lll]
        scale: 1.0

    wz_bb_lll:
        datacard name: "WZ_BB"
        systematics: common
        samples: [wz_bb_lll]
        scale: 1.0

    triboson:
        datacard name: "VVV"
        systematics: common
        samples: [www, wwz] #wzz, zzz
        scale: 1.0
 
#     ## Not enough MC events; makes combine tool seg fault
#     ttbarG:
#         datacard name: "TTG"
#         systematics: common
#         samples: [ttbarG]

#     ## Not enough MC events; makes combine tool seg fault
#     ttbarGStar:
#         datacard name: "TTGStar"
#         systematics: common
#         samples: [ttbarGStar_ee, ttbarGStar_mm, ttbarGStar_tt]

    ttbarWW:
        datacard name: "TTWW"
        color: kBlue-9
        systematics: common
        samples: [ttbarWW]
        scale: 1.0

    ttbarW:
        datacard name: "TTW"
        systematics: common
        samples: [ttbarW]
        scale: 1.0

#     ttH125_tt:
#         datacard name: "ttH_htt"
#         systematics: common
#         samples: [ttH125_tt]

#     ttH125_ZZ:
#         datacard name: "ttH_hzz"
#         systematics: common
#         samples: [ttH125_ZZ]

#     ttH125_WW:
#         datacard name: "ttH_hww"
#         systematics: common
#         samples: [ttH125_WW]

